spring:
   profiles:
      active: local
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: update
            format_sql: true
      show-sql: true
      generate-ddl: true
springdoc:
   swagger-ui:
      path: /swagger-ui.html